2025-08-20T19:30:06.9020746Z ##[group]Run actions/setup-python@v5
2025-08-20T19:30:06.9021019Z with:
2025-08-20T19:30:06.9021195Z   python-version: 3.11
2025-08-20T19:30:06.9021387Z   cache: pip
2025-08-20T19:30:06.9021613Z   cache-dependency-path: ./apps/api/requirements*.txt
2025-08-20T19:30:06.9021900Z   check-latest: false
2025-08-20T19:30:06.9022376Z   token: ***
2025-08-20T19:30:06.9022565Z   update-environment: true
2025-08-20T19:30:06.9022778Z   allow-prereleases: false
2025-08-20T19:30:06.9022980Z   freethreaded: false
2025-08-20T19:30:06.9023155Z env:
2025-08-20T19:30:06.9023316Z   PYTHON_VERSION: 3.11
2025-08-20T19:30:06.9023505Z   WORKING_DIR: ./apps/api
2025-08-20T19:30:06.9023697Z ##[endgroup]
2025-08-20T19:30:07.0654337Z ##[group]Installed versions
2025-08-20T19:30:07.0761673Z Successfully set up CPython (3.11.13)
2025-08-20T19:30:07.0762426Z ##[endgroup]
2025-08-20T19:30:07.1098029Z [command]/opt/hostedtoolcache/Python/3.11.13/x64/bin/pip cache dir
2025-08-20T19:30:07.3891156Z /home/runner/.cache/pip
2025-08-20T19:30:07.4983951Z pip cache is not found
